- name: 'fedit'
  num_clients: 80
  num_clients_per_task: 10
  m: 0.1
  rounds: 60
  local_step: 50
  batch_or_epoch: 'batch'
  equal_weight: false
  dataset: 'dolly'
  batch_size: 1
  max_length: 1024
  use_prompts: true
  iid: 'dir0.5'
  zerotask: 7
  dataset_subsample: 1.0
  model: 'google/gemma-2-2b-it'
  lr: 3e-04
  weight_decay: 0.0
  grad_clip: -100.0
  K: 4096
  zo_eps: 0.0005
  bias_sampling: false
  bias_loss_clip: 1000.0
  grad_initial: 0.0
  device: 0
  log: false
  log_root: 'logs'
  seed: 42
  eval_metric: 'rouge'
  save: false
  r: 16
  project: 'MIRA2'
