- name: 'ptuning'
  num_clients: 80
  num_clients_per_task: 10
  m: 0.1
  rounds: 60
  local_step: 5
  batch_or_epoch: 'batch'
  equal_weight: false
  dataset: 'instruct'
  batch_size: 8
  max_length: 1024
  use_prompts: true
  iid: 'dir0.5'
  zerotask: 7
  dataset_subsample: 1.0
  model: 'openai-community/gpt2'
  lr: 1e-3
  weight_decay: 1e-2
  grad_clip: -100.0
  K: 4096
  zo_eps: 0.0005
  bias_sampling: false
  bias_loss_clip: 1000.0
  grad_initial: 0.0
  device: 0
  log: false
  log_root: 'logs/ptuning/instruct/llama'
  output_dir: '/scratch/project_2009050/ptuning/instruct/gemma'
  seed: 42
  eval_metric: 'rouge'
  save: false
  r: 16
  project: 'MIRA2'
